In [2]:
import pandas as pd
import numpy as np
import csv

In [5]:
df_license_time = pd.read_excel("./data/traffic_accident_time.xls", engine="xlrd")

In [6]:
df_license_time = df_license_time.iloc[1:-4]
df_license_time.rename(columns={"기본계획 연령별1": "age_group", "기준년도": "accident_type"}, inplace=True)

In [7]:
df_license_time

,age_group,accident_type,2019,2019.1,2019.2,2019.3,2019.4,2019.5,2019.6,2019.7,...,2023.3,2023.4,2023.5,2023.6,2023.7,2023.8,2023.9,2023.10,2023.11,2023.12
1,합계,사고[건],229600,9708,5703,6359,13178,23971,22271,24044,...,4686,11511,21524,20569,22438,23429,27016,27405,17619,11646
2,합계,사망[명],3349,223,172,262,303,269,318,255,...,193,210,238,258,221,249,226,261,202,191
3,합계,부상[명],341712,14972,8668,9285,18962,34851,33332,36842,...,6459,15897,30196,29734,33161,34326,38962,38590,24734,16586
4,20세이하,사고[건],7231,485,370,267,234,383,320,490,...,157,188,402,263,416,579,858,895,691,572
5,20세이하,사망[명],95,8,16,12,5,4,2,3,...,3,3,5,2,2,5,4,3,7,6
6,20세이하,부상[명],10488,756,587,402,345,566,462,715,...,208,253,527,376,579,715,1104,1219,923,802
7,21~30세,사고[건],30631,2187,1410,1166,1730,2643,2078,2648,...,797,1419,2286,1784,2253,2363,2975,3826,2645,2159
8,21~30세,사망[명],376,50,49,37,29,20,28,17,...,34,23,19,17,13,17,20,33,16,33
9,21~30세,부상[명],47618,3425,2160,1804,2636,4055,3333,4268,...,1185,2056,3360,2751,3460,3677,4450,5554,3820,3131
10,31~40세,사고[건],34978,1805,1007,936,1868,3650,2981,3433,...,640,1562,3072,2425,2889,2882,3474,4029,2665,2060
11,31~40세,사망[명],429,44,34,36,34,29,27,20,...,14,19,22,17,11,28,18,32,27,30
12,31~40세,부상[명],52847,2749,1496,1367,2730,5452,4556,5361,...,907,2137,4461,3611,4323,4312,5112,5771,3793,3019
13,41~50세,사고[건],43769,1628,863,966,2520,4734,4155,4599,...,674,1929,3798,3339,3630,3760,4441,4768,3274,2159
14,41~50세,사망[명],584,39,26,40,55,41,52,40,...,32,21,34,33,18,29,26,30,31,49
15,41~50세,부상[명],65421,2648,1366,1390,3556,6811,6272,7092,...,897,2591,5356,4962,5379,5484,6515,6706,4660,3060
16,51~60세,사고[건],55814,1978,1055,1381,3410,5897,5653,5864,...,904,2738,4763,4777,5081,5276,6376,6298,4074,2349
17,51~60세,사망[명],790,50,21,61,78,59,79,61,...,51,53,67,57,50,49,50,57,58,35
18,51~60세,부상[명],83076,3036,1618,2008,4954,8653,8528,9072,...,1237,3761,6618,6894,7564,7685,9098,8797,5678,3351
19,61~64세,사고[건],19847,692,407,581,1238,2093,2154,2261,...,499,1216,2190,2286,2390,2617,2903,2695,1619,880
20,61~64세,사망[명],305,19,9,30,38,20,24,25,...,15,28,25,33,18,24,13,26,27,15
21,61~64세,부상[명],29513,1081,595,839,1774,2929,3201,3485,...,694,1730,3035,3238,3507,3893,4176,3832,2256,1260
22,65세이상,사고[건],33239,717,450,911,1958,4227,4657,4448,...,919,2294,4811,5527,5591,5734,5674,4412,2256,1232
23,65세이상,사망[명],769,13,17,46,64,96,106,89,...,44,63,66,99,109,97,95,80,36,23
24,65세이상,부상[명],48223,1045,679,1301,2734,6019,6679,6518,...,1218,3186,6624,7715,8144,8325,8160,6163,3166,1695

In [8]:
df_license_time["total"] = (df_license_time["2019"] + df_license_time["2020"]  + df_license_time["2021"] + df_license_time["2022"] + df_license_time["2023"]) / 5
df_license_time = df_license_time.drop(columns=["2019", "2020", "2021", "2022", "2023"])
df_license_time["time_0_2"] = (df_license_time["2019.1"] + df_license_time["2020.1"]  + df_license_time["2021.1"] + df_license_time["2022.1"] + df_license_time["2023.1"]) / 5
df_license_time = df_license_time.drop(columns=["2019.1", "2020.1", "2021.1", "2022.1", "2023.1"])
df_license_time["time_2_4"] = (df_license_time["2019.2"] + df_license_time["2020.2"]  + df_license_time["2021.2"] + df_license_time["2022.2"] + df_license_time["2023.2"]) / 5
df_license_time = df_license_time.drop(columns=["2019.2", "2020.2", "2021.2", "2022.2", "2023.2"])
df_license_time["time_4_6"] = (df_license_time["2019.3"] + df_license_time["2020.3"]  + df_license_time["2021.3"] + df_license_time["2022.3"] + df_license_time["2023.3"]) / 5
df_license_time = df_license_time.drop(columns=["2019.3", "2020.3", "2021.3", "2022.3", "2023.3"])
df_license_time["time_6_8"] = (df_license_time["2019.4"] + df_license_time["2020.4"]  + df_license_time["2021.4"] + df_license_time["2022.4"] + df_license_time["2023.4"]) / 5
df_license_time = df_license_time.drop(columns=["2019.4", "2020.4", "2021.4", "2022.4", "2023.4"])
df_license_time["time_8_10"] = (df_license_time["2019.5"] + df_license_time["2020.5"]  + df_license_time["2021.5"] + df_license_time["2022.5"] + df_license_time["2023.5"]) / 5
df_license_time = df_license_time.drop(columns=["2019.5", "2020.5", "2021.5", "2022.5", "2023.5"])
df_license_time["time_10_12"] = (df_license_time["2019.6"] + df_license_time["2020.6"]  + df_license_time["2021.6"] + df_license_time["2022.6"] + df_license_time["2023.6"]) / 5
df_license_time = df_license_time.drop(columns=["2019.6", "2020.6", "2021.6", "2022.6", "2023.6"])
df_license_time["time_12_14"] = (df_license_time["2019.7"] + df_license_time["2020.7"]  + df_license_time["2021.7"] + df_license_time["2022.7"] + df_license_time["2023.7"]) / 5
df_license_time = df_license_time.drop(columns=["2019.7", "2020.7", "2021.7", "2022.7", "2023.7"])
df_license_time["time_14_16"] = (df_license_time["2019.8"] + df_license_time["2020.8"]  + df_license_time["2021.8"] + df_license_time["2022.8"] + df_license_time["2023.8"]) / 5
df_license_time = df_license_time.drop(columns=["2019.8", "2020.8", "2021.8", "2022.8", "2023.8"])
df_license_time["time_16_18"] = (df_license_time["2019.9"] + df_license_time["2020.9"]  + df_license_time["2021.9"] + df_license_time["2022.9"] + df_license_time["2023.9"]) / 5
df_license_time = df_license_time.drop(columns=["2019.9", "2020.9", "2021.9", "2022.9", "2023.9"])
df_license_time["time_18_20"] = (df_license_time["2019.10"] + df_license_time["2020.10"]  + df_license_time["2021.10"] + df_license_time["2022.10"] + df_license_time["2023.10"]) / 5
df_license_time = df_license_time.drop(columns=["2019.10", "2020.10", "2021.10", "2022.10", "2023.10"])
df_license_time["time_20_22"] = (df_license_time["2019.11"] + df_license_time["2020.11"]  + df_license_time["2021.11"] + df_license_time["2022.11"] + df_license_time["2023.11"]) / 5
df_license_time = df_license_time.drop(columns=["2019.11", "2020.11", "2021.11", "2022.11", "2023.11"])
df_license_time["time_22_24"] = (df_license_time["2019.12"] + df_license_time["2020.12"]  + df_license_time["2021.12"] + df_license_time["2022.12"] + df_license_time["2023.12"]) / 5
df_license_time = df_license_time.drop(columns=["2019.12", "2020.12", "2021.12", "2022.12", "2023.12"])

In [9]:
df_license_time

,age_group,accident_type,total,time_0_2,time_2_4,time_4_6,time_6_8,time_8_10,time_10_12,time_12_14,time_14_16,time_16_18,time_18_20,time_20_22,time_22_24
1,합계,사고[건],207503.2,7576.0,4125.6,4879.6,11517.2,21086.8,20877.8,22931.2,24346.0,27453.0,29204.6,19784.8,13720.6
2,합계,사망[명],2926.4,187.0,144.2,212.8,249.8,245.2,274.6,259.4,282.0,264.4,318.8,263.8,224.4
3,합계,부상[명],301023.2,11394.6,6061.0,6831.2,16002.2,29890.0,30332.4,34021.6,36212.2,40150.4,41469.4,28491.6,20166.6
4,20세이하,사고[건],6677.8,417.6,292.4,214.2,201.4,350.2,306.0,491.6,681.2,965.8,1106.2,912.4,738.8
5,20세이하,사망[명],83.0,9.0,11.4,9.6,4.8,3.2,2.2,3.0,5.8,5.6,6.8,10.4,11.2
6,20세이하,부상[명],9409.2,650.6,452.2,319.0,287.2,480.0,437.2,692.6,921.2,1302.6,1514.8,1275.2,1076.6
7,21~30세,사고[건],28272.2,1814.4,1094.2,879.8,1457.6,2341.8,1980.0,2577.4,2631.0,3175.4,4291.8,3268.4,2760.4
8,21~30세,사망[명],350.4,48.6,41.6,33.4,23.2,17.4,20.2,19.2,17.6,19.0,38.6,32.0,39.6
9,21~30세,부상[명],42494.6,2766.8,1637.4,1300.0,2132.4,3458.2,3045.8,3983.2,4118.6,4860.6,6249.6,4801.0,4141.0
10,31~40세,사고[건],30591.8,1454.6,759.2,695.0,1612.4,3083.2,2621.6,3138.4,3248.0,3788.6,4508.6,3170.0,2512.2
11,31~40세,사망[명],347.8,34.4,24.8,25.0,25.6,25.2,20.8,19.6,27.4,24.4,41.2,42.2,37.2
12,31~40세,부상[명],45136.4,2184.4,1104.4,983.4,2267.6,4488.6,3940.6,4739.2,4911.4,5674.0,6457.0,4614.6,3771.2
13,41~50세,사고[건],37125.6,1230.4,600.8,715.8,2061.2,3931.2,3591.6,4080.4,4226.6,4867.0,5425.6,3786.2,2608.8
14,41~50세,사망[명],467.6,32.2,23.6,32.8,41.8,34.0,39.4,36.6,38.2,38.8,48.2,50.8,51.2
15,41~50세,부상[명],54031.6,1873.6,879.0,982.0,2837.4,5555.4,5277.2,6086.0,6311.6,7178.8,7735.6,5474.4,3840.6
16,51~60세,사고[건],48415.2,1369.0,683.4,1014.8,2872.6,4995.0,5112.6,5397.4,5859.2,6761.4,6922.6,4608.8,2818.4
17,51~60세,사망[명],659.8,35.2,23.0,46.8,62.0,59.0,62.8,55.8,61.2,60.8,77.2,69.6,46.4
18,51~60세,부상[명],70143.8,2043.6,1004.4,1420.8,3966.2,7087.2,7420.4,8013.8,8712.4,9831.6,9821.8,6675.4,4146.2
19,61~64세,사고[건],19161.2,501.2,262.0,472.8,1166.6,2024.4,2179.4,2274.8,2481.0,2714.2,2563.4,1610.2,911.2
20,61~64세,사망[명],281.8,13.4,6.2,21.4,28.0,25.4,30.2,27.2,28.8,28.2,33.0,24.0,16.0
21,61~64세,부상[명],27763.4,759.2,377.2,660.4,1626.2,2823.4,3154.0,3388.8,3724.4,3944.6,3647.0,2329.0,1329.2
22,65세이상,사고[건],34083.6,623.2,345.0,781.6,1978.0,4133.0,4882.2,4746.4,4945.8,4812.4,3812.8,1970.4,1052.8
23,65세이상,사망[명],735.6,14.2,13.6,43.8,64.4,81.0,99.0,98.0,103.0,87.4,73.6,34.8,22.8
24,65세이상,부상[명],48510.6,930.0,504.2,1045.4,2699.0,5751.8,6834.6,6870.8,7215.4,6949.0,5400.0,2803.6,1506.8

In [10]:
df_license_time["age_group"] = df_license_time["age_group"].replace({"합계": "all_age", "20세이하": 10, "21~30세": 20, "31~40세": 30, "41~50세": 40, "51~60세": 50, "61~64세": 60, "65세이상": 65})
df_license_time["accident_type"] = df_license_time["accident_type"].replace({"사고[건]": "accident", "사망[명]": "dead", "부상[명]": "injured"})
df_license_time = df_license_time.set_index("age_group")

In [11]:
df_license_time

,accident_type,total,time_0_2,time_2_4,time_4_6,time_6_8,time_8_10,time_10_12,time_12_14,time_14_16,time_16_18,time_18_20,time_20_22,time_22_24
age_group,,,,,,,,,,,,,,
all_age,accident,207503.2,7576.0,4125.6,4879.6,11517.2,21086.8,20877.8,22931.2,24346.0,27453.0,29204.6,19784.8,13720.6
all_age,dead,2926.4,187.0,144.2,212.8,249.8,245.2,274.6,259.4,282.0,264.4,318.8,263.8,224.4
all_age,injured,301023.2,11394.6,6061.0,6831.2,16002.2,29890.0,30332.4,34021.6,36212.2,40150.4,41469.4,28491.6,20166.6
10,accident,6677.8,417.6,292.4,214.2,201.4,350.2,306.0,491.6,681.2,965.8,1106.2,912.4,738.8
10,dead,83.0,9.0,11.4,9.6,4.8,3.2,2.2,3.0,5.8,5.6,6.8,10.4,11.2
10,injured,9409.2,650.6,452.2,319.0,287.2,480.0,437.2,692.6,921.2,1302.6,1514.8,1275.2,1076.6
20,accident,28272.2,1814.4,1094.2,879.8,1457.6,2341.8,1980.0,2577.4,2631.0,3175.4,4291.8,3268.4,2760.4
20,dead,350.4,48.6,41.6,33.4,23.2,17.4,20.2,19.2,17.6,19.0,38.6,32.0,39.6
20,injured,42494.6,2766.8,1637.4,1300.0,2132.4,3458.2,3045.8,3983.2,4118.6,4860.6,6249.6,4801.0,4141.0
30,accident,30591.8,1454.6,759.2,695.0,1612.4,3083.2,2621.6,3138.4,3248.0,3788.6,4508.6,3170.0,2512.2
30,dead,347.8,34.4,24.8,25.0,25.6,25.2,20.8,19.6,27.4,24.4,41.2,42.2,37.2
30,injured,45136.4,2184.4,1104.4,983.4,2267.6,4488.6,3940.6,4739.2,4911.4,5674.0,6457.0,4614.6,3771.2
40,accident,37125.6,1230.4,600.8,715.8,2061.2,3931.2,3591.6,4080.4,4226.6,4867.0,5425.6,3786.2,2608.8
40,dead,467.6,32.2,23.6,32.8,41.8,34.0,39.4,36.6,38.2,38.8,48.2,50.8,51.2
40,injured,54031.6,1873.6,879.0,982.0,2837.4,5555.4,5277.2,6086.0,6311.6,7178.8,7735.6,5474.4,3840.6
50,accident,48415.2,1369.0,683.4,1014.8,2872.6,4995.0,5112.6,5397.4,5859.2,6761.4,6922.6,4608.8,2818.4
50,dead,659.8,35.2,23.0,46.8,62.0,59.0,62.8,55.8,61.2,60.8,77.2,69.6,46.4
50,injured,70143.8,2043.6,1004.4,1420.8,3966.2,7087.2,7420.4,8013.8,8712.4,9831.6,9821.8,6675.4,4146.2
60,accident,19161.2,501.2,262.0,472.8,1166.6,2024.4,2179.4,2274.8,2481.0,2714.2,2563.4,1610.2,911.2
60,dead,281.8,13.4,6.2,21.4,28.0,25.4,30.2,27.2,28.8,28.2,33.0,24.0,16.0
60,injured,27763.4,759.2,377.2,660.4,1626.2,2823.4,3154.0,3388.8,3724.4,3944.6,3647.0,2329.0,1329.2
65,accident,34083.6,623.2,345.0,781.6,1978.0,4133.0,4882.2,4746.4,4945.8,4812.4,3812.8,1970.4,1052.8
65,dead,735.6,14.2,13.6,43.8,64.4,81.0,99.0,98.0,103.0,87.4,73.6,34.8,22.8
65,injured,48510.6,930.0,504.2,1045.4,2699.0,5751.8,6834.6,6870.8,7215.4,6949.0,5400.0,2803.6,1506.8

In [12]:
df_license_time.to_csv("./data/pre_traffic_accident_time.csv", encoding="utf-8")

In [13]:
df = pd.read_csv("./data/pre_traffic_accident_time.csv", encoding="utf-8")

In [14]:
df

,age_group,accident_type,total,time_0_2,time_2_4,time_4_6,time_6_8,time_8_10,time_10_12,time_12_14,time_14_16,time_16_18,time_18_20,time_20_22,time_22_24
0,all_age,accident,207503.2,7576.0,4125.6,4879.6,11517.2,21086.8,20877.8,22931.2,24346.0,27453.0,29204.6,19784.8,13720.6
1,all_age,dead,2926.4,187.0,144.2,212.8,249.8,245.2,274.6,259.4,282.0,264.4,318.8,263.8,224.4
2,all_age,injured,301023.2,11394.6,6061.0,6831.2,16002.2,29890.0,30332.4,34021.6,36212.2,40150.4,41469.4,28491.6,20166.6
3,10,accident,6677.8,417.6,292.4,214.2,201.4,350.2,306.0,491.6,681.2,965.8,1106.2,912.4,738.8
4,10,dead,83.0,9.0,11.4,9.6,4.8,3.2,2.2,3.0,5.8,5.6,6.8,10.4,11.2
5,10,injured,9409.2,650.6,452.2,319.0,287.2,480.0,437.2,692.6,921.2,1302.6,1514.8,1275.2,1076.6
6,20,accident,28272.2,1814.4,1094.2,879.8,1457.6,2341.8,1980.0,2577.4,2631.0,3175.4,4291.8,3268.4,2760.4
7,20,dead,350.4,48.6,41.6,33.4,23.2,17.4,20.2,19.2,17.6,19.0,38.6,32.0,39.6
8,20,injured,42494.6,2766.8,1637.4,1300.0,2132.4,3458.2,3045.8,3983.2,4118.6,4860.6,6249.6,4801.0,4141.0
9,30,accident,30591.8,1454.6,759.2,695.0,1612.4,3083.2,2621.6,3138.4,3248.0,3788.6,4508.6,3170.0,2512.2
10,30,dead,347.8,34.4,24.8,25.0,25.6,25.2,20.8,19.6,27.4,24.4,41.2,42.2,37.2
11,30,injured,45136.4,2184.4,1104.4,983.4,2267.6,4488.6,3940.6,4739.2,4911.4,5674.0,6457.0,4614.6,3771.2
12,40,accident,37125.6,1230.4,600.8,715.8,2061.2,3931.2,3591.6,4080.4,4226.6,4867.0,5425.6,3786.2,2608.8
13,40,dead,467.6,32.2,23.6,32.8,41.8,34.0,39.4,36.6,38.2,38.8,48.2,50.8,51.2
14,40,injured,54031.6,1873.6,879.0,982.0,2837.4,5555.4,5277.2,6086.0,6311.6,7178.8,7735.6,5474.4,3840.6
15,50,accident,48415.2,1369.0,683.4,1014.8,2872.6,4995.0,5112.6,5397.4,5859.2,6761.4,6922.6,4608.8,2818.4
16,50,dead,659.8,35.2,23.0,46.8,62.0,59.0,62.8,55.8,61.2,60.8,77.2,69.6,46.4
17,50,injured,70143.8,2043.6,1004.4,1420.8,3966.2,7087.2,7420.4,8013.8,8712.4,9831.6,9821.8,6675.4,4146.2
18,60,accident,19161.2,501.2,262.0,472.8,1166.6,2024.4,2179.4,2274.8,2481.0,2714.2,2563.4,1610.2,911.2
19,60,dead,281.8,13.4,6.2,21.4,28.0,25.4,30.2,27.2,28.8,28.2,33.0,24.0,16.0
20,60,injured,27763.4,759.2,377.2,660.4,1626.2,2823.4,3154.0,3388.8,3724.4,3944.6,3647.0,2329.0,1329.2
21,65,accident,34083.6,623.2,345.0,781.6,1978.0,4133.0,4882.2,4746.4,4945.8,4812.4,3812.8,1970.4,1052.8
22,65,dead,735.6,14.2,13.6,43.8,64.4,81.0,99.0,98.0,103.0,87.4,73.6,34.8,22.8
23,65,injured,48510.6,930.0,504.2,1045.4,2699.0,5751.8,6834.6,6870.8,7215.4,6949.0,5400.0,2803.6,1506.8