In [358]:
import pandas as pd
import numpy as np
import csv

In [520]:
df_traffic_type_5 = pd.read_excel("./data/traffic_accident_type_5.xls", engine="xlrd")

In [521]:
df_traffic_type_5 = df_traffic_type_5.iloc[:-2]
df_traffic_type_5 = df_traffic_type_5.replace("-", np.nan)
df_traffic_type_5 = df_traffic_type_5.fillna(0)

In [522]:
df_traffic_type_5

,기본계획 연령별1,2019,2019.1,2019.2,2019.3,2019.4,2019.5,2019.6,2019.7,2019.8,...,2023.10,2023.11,2023.12,2023.13,2023.14,2023.15,2023.16,2023.17,2023.18,2023.19
0,기본계획 연령별1,합계,과로,과속,앞지르기방법위반,앞지르기금지위반,중앙선침범,신호위반,안전거리미확보,일시정지위반,...,진로양보불이행,안전운전의무불이행,교차로운행방법위반,보행자보호의무위반,차로위반(진로변경),직진우회전진행방해,철길건널목통과방법,긴급차피양의무위반,기타,정비불량
1,합계,229600,1,1124,111,410,9344,27921,22473,581,...,29,110868,11060,7227,2641,5286,1,3,5637,8
2,20세이하,7231,0,69,8,22,370,1309,439,20,...,0,3232,171,185,32,130,0,0,409,0
3,21~30세,30631,0,326,13,58,1278,4214,2920,79,...,2,14051,1223,693,303,706,0,1,769,0
4,31~40세,34978,0,226,25,56,1335,4052,3576,97,...,4,15732,1417,936,282,763,0,0,691,0
5,41~50세,43769,0,173,21,64,1636,4842,4286,125,...,7,18762,1942,1414,411,953,0,0,832,4
6,51~60세,55814,1,184,22,98,2175,6625,5698,142,...,7,24582,2667,1653,686,1137,1,1,1308,0
7,61~64세,19847,0,63,7,38,816,2414,2013,54,...,2,11050,1212,746,274,516,0,0,586,2
8,65세이상,33239,0,83,13,71,1634,4162,3235,64,...,7,21653,2389,1445,622,1070,0,1,893,1

In [523]:
columns = df_traffic_type_5.iloc[0]
df_traffic_type_5.columns = columns
df_traffic_type_5 = df_traffic_type_5[2:]
df_traffic_type_5 = df_traffic_type_5.groupby(df_traffic_type_5.columns, axis=1).sum()

C:\Users\minni\AppData\Local\Temp\ipykernel_80808\2723475489.py:4: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_traffic_type_5 = df_traffic_type_5.groupby(df_traffic_type_5.columns, axis=1).sum()

In [524]:
df_traffic_type_5

,과로,과속,교차로운행방법위반,기본계획 연령별1,기타,긴급차피양의무위반,보행자보호의무위반,부당한회전,신호위반,안전거리미확보,...,앞지르기방법위반,우선권양보불이행,일시정지위반,정비불량,중앙선침범,직진우회전진행방해,진로양보불이행,차로위반(진로변경),철길건널목통과방법,합계
2,0,151,1359,20세이하,1423,1,837,393,5644,1920,...,27,8,85,0,1463,865,6,305,1,33389
3,3,727,7841,21~30세,3294,3,3721,802,19364,14090,...,99,10,505,3,5642,4394,21,1977,2,141361
4,0,497,9071,31~40세,3206,2,4963,883,17845,16353,...,103,8,538,8,5707,4577,35,2106,3,152959
5,1,321,12289,41~50세,4552,1,7055,1171,20781,19005,...,111,14,670,18,6729,5686,46,2824,0,185628
6,3,395,15970,51~60세,7057,2,8464,1753,27474,25716,...,113,13,786,8,9393,7013,45,4398,5,242076
7,3,112,6274,61~64세,2750,0,3402,786,11067,10499,...,40,7,270,8,3894,2907,25,1709,1,95806
8,1,162,11093,65세이상,3890,1,5915,1520,19971,18313,...,75,15,423,7,8131,5230,41,3131,4,170418

In [525]:
df_traffic_type_5.rename(columns={"기본계획 연령별1": "age_group"}, inplace=True)
df_traffic_type_5 = df_traffic_type_5.drop(columns=["합계"])

In [526]:
df_traffic_type_5

,과로,과속,교차로운행방법위반,age_group,기타,긴급차피양의무위반,보행자보호의무위반,부당한회전,신호위반,안전거리미확보,...,앞지르기금지위반,앞지르기방법위반,우선권양보불이행,일시정지위반,정비불량,중앙선침범,직진우회전진행방해,진로양보불이행,차로위반(진로변경),철길건널목통과방법
2,0,151,1359,20세이하,1423,1,837,393,5644,1920,...,75,27,8,85,0,1463,865,6,305,1
3,3,727,7841,21~30세,3294,3,3721,802,19364,14090,...,235,99,10,505,3,5642,4394,21,1977,2
4,0,497,9071,31~40세,3206,2,4963,883,17845,16353,...,233,103,8,538,8,5707,4577,35,2106,3
5,1,321,12289,41~50세,4552,1,7055,1171,20781,19005,...,270,111,14,670,18,6729,5686,46,2824,0
6,3,395,15970,51~60세,7057,2,8464,1753,27474,25716,...,413,113,13,786,8,9393,7013,45,4398,5
7,3,112,6274,61~64세,2750,0,3402,786,11067,10499,...,170,40,7,270,8,3894,2907,25,1709,1
8,1,162,11093,65세이상,3890,1,5915,1520,19971,18313,...,293,75,15,423,7,8131,5230,41,3131,4

In [527]:
df_traffic_type_5.columns = df_traffic_type_5.columns.str.replace(r"\([^)]*\)", "", regex=True).str.strip()

In [528]:
df_traffic_type_5

,과로,과속,교차로운행방법위반,age_group,기타,긴급차피양의무위반,보행자보호의무위반,부당한회전,신호위반,안전거리미확보,...,앞지르기금지위반,앞지르기방법위반,우선권양보불이행,일시정지위반,정비불량,중앙선침범,직진우회전진행방해,진로양보불이행,차로위반,철길건널목통과방법
2,0,151,1359,20세이하,1423,1,837,393,5644,1920,...,75,27,8,85,0,1463,865,6,305,1
3,3,727,7841,21~30세,3294,3,3721,802,19364,14090,...,235,99,10,505,3,5642,4394,21,1977,2
4,0,497,9071,31~40세,3206,2,4963,883,17845,16353,...,233,103,8,538,8,5707,4577,35,2106,3
5,1,321,12289,41~50세,4552,1,7055,1171,20781,19005,...,270,111,14,670,18,6729,5686,46,2824,0
6,3,395,15970,51~60세,7057,2,8464,1753,27474,25716,...,413,113,13,786,8,9393,7013,45,4398,5
7,3,112,6274,61~64세,2750,0,3402,786,11067,10499,...,170,40,7,270,8,3894,2907,25,1709,1
8,1,162,11093,65세이상,3890,1,5915,1520,19971,18313,...,293,75,15,423,7,8131,5230,41,3131,4

In [529]:
df_traffic_type_5["age_group"] = df_traffic_type_5["age_group"].replace({"20세이하": "10", "21~30세": "20", "31~40세": "30", "41~50세": "40", "51~60세": "50", "61~64세": "60", "65세이상": "65"})

In [530]:
df_traffic_type_5

,과로,과속,교차로운행방법위반,age_group,기타,긴급차피양의무위반,보행자보호의무위반,부당한회전,신호위반,안전거리미확보,...,앞지르기금지위반,앞지르기방법위반,우선권양보불이행,일시정지위반,정비불량,중앙선침범,직진우회전진행방해,진로양보불이행,차로위반,철길건널목통과방법
2,0,151,1359,10,1423,1,837,393,5644,1920,...,75,27,8,85,0,1463,865,6,305,1
3,3,727,7841,20,3294,3,3721,802,19364,14090,...,235,99,10,505,3,5642,4394,21,1977,2
4,0,497,9071,30,3206,2,4963,883,17845,16353,...,233,103,8,538,8,5707,4577,35,2106,3
5,1,321,12289,40,4552,1,7055,1171,20781,19005,...,270,111,14,670,18,6729,5686,46,2824,0
6,3,395,15970,50,7057,2,8464,1753,27474,25716,...,413,113,13,786,8,9393,7013,45,4398,5
7,3,112,6274,60,2750,0,3402,786,11067,10499,...,170,40,7,270,8,3894,2907,25,1709,1
8,1,162,11093,65,3890,1,5915,1520,19971,18313,...,293,75,15,423,7,8131,5230,41,3131,4

In [531]:
df_traffic_type_5 = df_traffic_type_5.set_index("age_group")

In [532]:
df_traffic_type_5

,과로,과속,교차로운행방법위반,기타,긴급차피양의무위반,보행자보호의무위반,부당한회전,신호위반,안전거리미확보,안전운전의무불이행,앞지르기금지위반,앞지르기방법위반,우선권양보불이행,일시정지위반,정비불량,중앙선침범,직진우회전진행방해,진로양보불이행,차로위반,철길건널목통과방법
age_group,,,,,,,,,,,,,,,,,,,,
10,0,151,1359,1423,1,837,393,5644,1920,18826,75,27,8,85,0,1463,865,6,305,1
20,3,727,7841,3294,3,3721,802,19364,14090,78628,235,99,10,505,3,5642,4394,21,1977,2
30,0,497,9071,3206,2,4963,883,17845,16353,86821,233,103,8,538,8,5707,4577,35,2106,3
40,1,321,12289,4552,1,7055,1171,20781,19005,104084,270,111,14,670,18,6729,5686,46,2824,0
50,3,395,15970,7057,2,8464,1753,27474,25716,133055,413,113,13,786,8,9393,7013,45,4398,5
60,3,112,6274,2750,0,3402,786,11067,10499,51882,170,40,7,270,8,3894,2907,25,1709,1
65,1,162,11093,3890,1,5915,1520,19971,18313,92202,293,75,15,423,7,8131,5230,41,3131,4

In [533]:
df_traffic_type_5.to_csv("./data/pre_traffic_accident_type_5.csv", encoding="utf-8")

In [534]:
df = pd.read_csv("./data/pre_traffic_accident_type_5.csv", encoding="utf-8")

In [535]:
df

,age_group,과로,과속,교차로운행방법위반,기타,긴급차피양의무위반,보행자보호의무위반,부당한회전,신호위반,안전거리미확보,...,앞지르기금지위반,앞지르기방법위반,우선권양보불이행,일시정지위반,정비불량,중앙선침범,직진우회전진행방해,진로양보불이행,차로위반,철길건널목통과방법
0,10,0,151,1359,1423,1,837,393,5644,1920,...,75,27,8,85,0,1463,865,6,305,1
1,20,3,727,7841,3294,3,3721,802,19364,14090,...,235,99,10,505,3,5642,4394,21,1977,2
2,30,0,497,9071,3206,2,4963,883,17845,16353,...,233,103,8,538,8,5707,4577,35,2106,3
3,40,1,321,12289,4552,1,7055,1171,20781,19005,...,270,111,14,670,18,6729,5686,46,2824,0
4,50,3,395,15970,7057,2,8464,1753,27474,25716,...,413,113,13,786,8,9393,7013,45,4398,5
5,60,3,112,6274,2750,0,3402,786,11067,10499,...,170,40,7,270,8,3894,2907,25,1709,1
6,65,1,162,11093,3890,1,5915,1520,19971,18313,...,293,75,15,423,7,8131,5230,41,3131,4