In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
df_traffic_type_5 = pd.read_excel("traffic_accident_type.xls", engine="xlrd")

In [3]:
df_traffic_type_5 = df_traffic_type_5.iloc[:-2]
df_traffic_type_5 = df_traffic_type_5.replace("-", np.nan)
df_traffic_type_5 = df_traffic_type_5.fillna(0)

In [4]:
columns = df_traffic_type_5.iloc[0]
df_traffic_type_5.columns = columns
df_traffic_type_5 = df_traffic_type_5[2:]
df_traffic_type_5 = df_traffic_type_5.groupby(df_traffic_type_5.columns, axis=1).sum()

C:\Users\minni\AppData\Local\Temp\ipykernel_155040\2723475489.py:4: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_traffic_type_5 = df_traffic_type_5.groupby(df_traffic_type_5.columns, axis=1).sum()

In [5]:
df_traffic_type_5.rename(columns={"기본계획 연령별1": "age_group"}, inplace=True)
df_traffic_type_5 = df_traffic_type_5.drop(columns=["합계"])

In [6]:
df_traffic_type_5.columns = df_traffic_type_5.columns.str.replace(r"\([^)]*\)", "", regex=True).str.strip()

In [7]:
df_traffic_type_5["age_group"] = df_traffic_type_5["age_group"].replace({"20세이하": "10", "21~30세": "20", "31~40세": "30", "41~50세": "40", "51~60세": "50", "61~64세": "60", "65세이상": "65"})

In [8]:
df_traffic_type_5 = df_traffic_type_5.set_index("age_group")

In [9]:
df_traffic_type_5

,과로,과속,교차로운행방법위반,기타,긴급차피양의무위반,보행자보호의무위반,부당한회전,신호위반,안전거리미확보,안전운전의무불이행,앞지르기금지위반,앞지르기방법위반,우선권양보불이행,일시정지위반,정비불량,중앙선침범,직진우회전진행방해,진로양보불이행,차로위반,철길건널목통과방법
age_group,,,,,,,,,,,,,,,,,,,,
10,0,151,1359,1423,1,837,393,5644,1920,18826,75,27,8,85,0,1463,865,6,305,1
20,3,727,7841,3294,3,3721,802,19364,14090,78628,235,99,10,505,3,5642,4394,21,1977,2
30,0,497,9071,3206,2,4963,883,17845,16353,86821,233,103,8,538,8,5707,4577,35,2106,3
40,1,321,12289,4552,1,7055,1171,20781,19005,104084,270,111,14,670,18,6729,5686,46,2824,0
50,3,395,15970,7057,2,8464,1753,27474,25716,133055,413,113,13,786,8,9393,7013,45,4398,5
60,3,112,6274,2750,0,3402,786,11067,10499,51882,170,40,7,270,8,3894,2907,25,1709,1
65,1,162,11093,3890,1,5915,1520,19971,18313,92202,293,75,15,423,7,8131,5230,41,3131,4

In [10]:
df_traffic_type_5.to_csv("pre_traffic_accident_type.csv", encoding="utf-8")