In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
df_license_time = pd.read_excel("traffic_accident_time.xls", engine="xlrd")

In [3]:
df_license_time = df_license_time.iloc[1:-4]
df_license_time.rename(columns={"기본계획 연령별1": "age_group", "기준년도": "accident_type"}, inplace=True)

In [4]:
df_license_time["total"] = (df_license_time["2019"] + df_license_time["2020"]  + df_license_time["2021"] + df_license_time["2022"] + df_license_time["2023"]) / 5
df_license_time = df_license_time.drop(columns=["2019", "2020", "2021", "2022", "2023"])
df_license_time["time_0_2"] = (df_license_time["2019.1"] + df_license_time["2020.1"]  + df_license_time["2021.1"] + df_license_time["2022.1"] + df_license_time["2023.1"]) / 5
df_license_time = df_license_time.drop(columns=["2019.1", "2020.1", "2021.1", "2022.1", "2023.1"])
df_license_time["time_2_4"] = (df_license_time["2019.2"] + df_license_time["2020.2"]  + df_license_time["2021.2"] + df_license_time["2022.2"] + df_license_time["2023.2"]) / 5
df_license_time = df_license_time.drop(columns=["2019.2", "2020.2", "2021.2", "2022.2", "2023.2"])
df_license_time["time_4_6"] = (df_license_time["2019.3"] + df_license_time["2020.3"]  + df_license_time["2021.3"] + df_license_time["2022.3"] + df_license_time["2023.3"]) / 5
df_license_time = df_license_time.drop(columns=["2019.3", "2020.3", "2021.3", "2022.3", "2023.3"])
df_license_time["time_6_8"] = (df_license_time["2019.4"] + df_license_time["2020.4"]  + df_license_time["2021.4"] + df_license_time["2022.4"] + df_license_time["2023.4"]) / 5
df_license_time = df_license_time.drop(columns=["2019.4", "2020.4", "2021.4", "2022.4", "2023.4"])
df_license_time["time_8_10"] = (df_license_time["2019.5"] + df_license_time["2020.5"]  + df_license_time["2021.5"] + df_license_time["2022.5"] + df_license_time["2023.5"]) / 5
df_license_time = df_license_time.drop(columns=["2019.5", "2020.5", "2021.5", "2022.5", "2023.5"])
df_license_time["time_10_12"] = (df_license_time["2019.6"] + df_license_time["2020.6"]  + df_license_time["2021.6"] + df_license_time["2022.6"] + df_license_time["2023.6"]) / 5
df_license_time = df_license_time.drop(columns=["2019.6", "2020.6", "2021.6", "2022.6", "2023.6"])
df_license_time["time_12_14"] = (df_license_time["2019.7"] + df_license_time["2020.7"]  + df_license_time["2021.7"] + df_license_time["2022.7"] + df_license_time["2023.7"]) / 5
df_license_time = df_license_time.drop(columns=["2019.7", "2020.7", "2021.7", "2022.7", "2023.7"])
df_license_time["time_14_16"] = (df_license_time["2019.8"] + df_license_time["2020.8"]  + df_license_time["2021.8"] + df_license_time["2022.8"] + df_license_time["2023.8"]) / 5
df_license_time = df_license_time.drop(columns=["2019.8", "2020.8", "2021.8", "2022.8", "2023.8"])
df_license_time["time_16_18"] = (df_license_time["2019.9"] + df_license_time["2020.9"]  + df_license_time["2021.9"] + df_license_time["2022.9"] + df_license_time["2023.9"]) / 5
df_license_time = df_license_time.drop(columns=["2019.9", "2020.9", "2021.9", "2022.9", "2023.9"])
df_license_time["time_18_20"] = (df_license_time["2019.10"] + df_license_time["2020.10"]  + df_license_time["2021.10"] + df_license_time["2022.10"] + df_license_time["2023.10"]) / 5
df_license_time = df_license_time.drop(columns=["2019.10", "2020.10", "2021.10", "2022.10", "2023.10"])
df_license_time["time_20_22"] = (df_license_time["2019.11"] + df_license_time["2020.11"]  + df_license_time["2021.11"] + df_license_time["2022.11"] + df_license_time["2023.11"]) / 5
df_license_time = df_license_time.drop(columns=["2019.11", "2020.11", "2021.11", "2022.11", "2023.11"])
df_license_time["time_22_24"] = (df_license_time["2019.12"] + df_license_time["2020.12"]  + df_license_time["2021.12"] + df_license_time["2022.12"] + df_license_time["2023.12"]) / 5
df_license_time = df_license_time.drop(columns=["2019.12", "2020.12", "2021.12", "2022.12", "2023.12"])

In [5]:
df_license_time["age_group"] = df_license_time["age_group"].replace({"합계": "all_age", "20세이하": 10, "21~30세": 20, "31~40세": 30, "41~50세": 40, "51~60세": 50, "61~64세": 60, "65세이상": 65})
df_license_time["accident_type"] = df_license_time["accident_type"].replace({"사고[건]": "accident", "사망[명]": "dead", "부상[명]": "injured"})
df_license_time = df_license_time.set_index("age_group")

In [6]:
df_license_time

,accident_type,total,time_0_2,time_2_4,time_4_6,time_6_8,time_8_10,time_10_12,time_12_14,time_14_16,time_16_18,time_18_20,time_20_22,time_22_24
age_group,,,,,,,,,,,,,,
all_age,accident,207503.2,7576.0,4125.6,4879.6,11517.2,21086.8,20877.8,22931.2,24346.0,27453.0,29204.6,19784.8,13720.6
all_age,dead,2926.4,187.0,144.2,212.8,249.8,245.2,274.6,259.4,282.0,264.4,318.8,263.8,224.4
all_age,injured,301023.2,11394.6,6061.0,6831.2,16002.2,29890.0,30332.4,34021.6,36212.2,40150.4,41469.4,28491.6,20166.6
10,accident,6677.8,417.6,292.4,214.2,201.4,350.2,306.0,491.6,681.2,965.8,1106.2,912.4,738.8
10,dead,83.0,9.0,11.4,9.6,4.8,3.2,2.2,3.0,5.8,5.6,6.8,10.4,11.2
10,injured,9409.2,650.6,452.2,319.0,287.2,480.0,437.2,692.6,921.2,1302.6,1514.8,1275.2,1076.6
20,accident,28272.2,1814.4,1094.2,879.8,1457.6,2341.8,1980.0,2577.4,2631.0,3175.4,4291.8,3268.4,2760.4
20,dead,350.4,48.6,41.6,33.4,23.2,17.4,20.2,19.2,17.6,19.0,38.6,32.0,39.6
20,injured,42494.6,2766.8,1637.4,1300.0,2132.4,3458.2,3045.8,3983.2,4118.6,4860.6,6249.6,4801.0,4141.0
30,accident,30591.8,1454.6,759.2,695.0,1612.4,3083.2,2621.6,3138.4,3248.0,3788.6,4508.6,3170.0,2512.2
30,dead,347.8,34.4,24.8,25.0,25.6,25.2,20.8,19.6,27.4,24.4,41.2,42.2,37.2
30,injured,45136.4,2184.4,1104.4,983.4,2267.6,4488.6,3940.6,4739.2,4911.4,5674.0,6457.0,4614.6,3771.2
40,accident,37125.6,1230.4,600.8,715.8,2061.2,3931.2,3591.6,4080.4,4226.6,4867.0,5425.6,3786.2,2608.8
40,dead,467.6,32.2,23.6,32.8,41.8,34.0,39.4,36.6,38.2,38.8,48.2,50.8,51.2
40,injured,54031.6,1873.6,879.0,982.0,2837.4,5555.4,5277.2,6086.0,6311.6,7178.8,7735.6,5474.4,3840.6
50,accident,48415.2,1369.0,683.4,1014.8,2872.6,4995.0,5112.6,5397.4,5859.2,6761.4,6922.6,4608.8,2818.4
50,dead,659.8,35.2,23.0,46.8,62.0,59.0,62.8,55.8,61.2,60.8,77.2,69.6,46.4
50,injured,70143.8,2043.6,1004.4,1420.8,3966.2,7087.2,7420.4,8013.8,8712.4,9831.6,9821.8,6675.4,4146.2
60,accident,19161.2,501.2,262.0,472.8,1166.6,2024.4,2179.4,2274.8,2481.0,2714.2,2563.4,1610.2,911.2
60,dead,281.8,13.4,6.2,21.4,28.0,25.4,30.2,27.2,28.8,28.2,33.0,24.0,16.0
60,injured,27763.4,759.2,377.2,660.4,1626.2,2823.4,3154.0,3388.8,3724.4,3944.6,3647.0,2329.0,1329.2
65,accident,34083.6,623.2,345.0,781.6,1978.0,4133.0,4882.2,4746.4,4945.8,4812.4,3812.8,1970.4,1052.8
65,dead,735.6,14.2,13.6,43.8,64.4,81.0,99.0,98.0,103.0,87.4,73.6,34.8,22.8
65,injured,48510.6,930.0,504.2,1045.4,2699.0,5751.8,6834.6,6870.8,7215.4,6949.0,5400.0,2803.6,1506.8

In [7]:
df_license_time.to_csv("pre_traffic_accident_time.csv", encoding="utf-8")